require 'vagrant-openstack-provider'

Vagrant.configure('2') do |config|
  config.ssh.username = 'ubuntu'  
  config.ssh.private_key_path = "C:/Users/devops/.ssh/id_rsa"
  config.vm.provider :openstack do |os, override|
    os.identity_api_version = ENV['OS_IDENTITY_API_VERSION']
    os.openstack_auth_url = ENV['OS_AUTH_URL']
    os.domain_name        = ENV['OS_DOMAIN_NAME']
    os.username           = ENV['OS_USERNAME']
    os.password           = ENV['OS_PASSWORD']
    os.tenant_name        = ENV['OS_TENANT_NAME']
    os.project_name       = ENV['OS_PROJECT_NAME']
    os.keypair_name       = ENV['OS_KEY_PAIR_NAME']
    os.region             = ENV['OS_REGION_NAME']
    os.image              = ENV['OS_IMAGE']
  end
  config.vm.define 'linux_server_1' do |s|
    s.vm.provider :openstack do |os, override|
      os.server_name = 'jimena-devops-vm-1'
      os.flavor = 'f2.desktop.medium'
      override.vm.synced_folder '.', '/vagrant', disabled: true
    end
  end
end
